DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS books;

CREATE TABLE author (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    genre TEXT NOT NULL
);

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    publisher TEXT NOT NULL,
    author_id BIGINT NOT NULL REFERENCES authors(id) 
);